# This workflow will run tests using Node.js and publish the package to npm when a release is created
# For more information see: https://docs.github.com/en/actions/tutorials/publish-packages/publish-nodejs-packages

name: Node.js Package

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: 24
            - run: npm ci
            - run: npm test

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: 24
                  registry-url: https://registry.npmjs.org
                  package-manager-cache: false
            - run: npm ci
            - run: npm run build
            - run: npm publish --access public
